### ISSUE TITLE
Chart outdated - mongoDB chart version (10.x) was removed on bitnami

### ISSUE THREAD

**Issue by Nightreaver** [wekan/charts#10]
I recently tried to deploy the latest Chart from "main" and I noticed that the deployment failed due to mongo-db issues.
Currently the Chart.yaml contains 

```
dependencies:
  - condition: mongodb.enabled
    name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 10.0.x
```

Checking in bitnami ( https://artifacthub.io/packages/helm/bitnami/mongodb ), I can see the oldest available version is 12.XX

So the Chart should be updated to v. 12 or v. 13 accordingly.
