### ISSUE TITLE
[Feature] Add readiness probe to deployment

### ISSUE THREAD

**Issue by markksuite** [wekan/charts#26]
Add readinessProbe to deployment.yaml:

```
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
```
