### ISSUE TITLE
Readiness/liveliness probes fail when using subpath

### ISSUE THREAD

**Issue by emoritzx** [wekan/charts#30]
When configuring the Helm values to run wekan under a subpath, the readiness and liveliness probes are still configured to call the root path `/`. This returns a `404 Not Found` and results in the probe(s) failing, which ultimately results in Kubernetes killing the pod.

Relevent config:
```yaml
# values.yml
endpoint: my.website.com
root_url: https://my.website.com/wekan
ingress:
  path: /wekan
  hosts: [ my.website.com ]
```

When I manually updated the deployment to set the readiness/liveliness probe URL to `/wekan`, then everything worked.
